aws:
  region_name: ${AWS_DEFAULT_REGION:ap-southeast-1}

s3:
  bucket_name: ${S3_BUCKET_NAME}
  data_prefix: data
  processed_folder: processed

datasets:
  puzzle-pieces-picker:
    source:
      type: url
      path: https://figshare.com/ndownloader/files/44894080
    unzip_password: null
  m5hisdoc:
    source:
      type: s3
      path: data/M5HisDoc.zip
    unzip_password: ${M5HISDOC_PASSWORD}
    batch_size: 1000
  casia-hwdb:
    source:
      type: url
      path:
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.0TrainPart1.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.0TrainPart2.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.0TrainPart3.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.1TrainPart1.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.1TrainPart2.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.1TrainPart3.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.2TrainPart1.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.2TrainPart2.zip
        - https://nlpr.ia.ac.cn/databases/Download/Offline/CharData/Gnt1.2TrainPart3.zip
    unzip_password: null
    batch_size: 100

processing:
  num_workers: 64
  batch_size: 1000
  max_pool_connections: 500
  max_concurrency: 64
  concurrent_batches: 8  # New parameter for controlling concurrent batch processing
  chunk_size: 268435456  # 64MB
  multipart_threshold: 33554432  # 8MB
  multipart_chunksize: 33554432  # 8MB
  buffer_size: 16777216  # 8MB (8 * 1024 * 1024)
  buffer_pool_size: 128
  small_file_threshold: 314572800  # 300MB

dynamodb:
  table_name: ETLJobTracker
